### ISSUE TITLE
How to set Content height to adjust the tabviewcontrol height

### ISSUE THREAD

**Issue by masiri201** [chaosifier/TabView#2]
Hey i really like your custom control, but, the content doesnt scale automatically with the control height, i tried to do it multiple ways but wasn't successfull, if you have the time please respond or update the control to have a property that sets the content height to fit the tabviewcontrol.

**Comment by chaosifier** [comment]
Have you tried setting the VerticalOptions property to FillAndExpand?

**Comment by TheRealNyquist** [comment]
Had the same issue. My content views were set to FillAndExpand, but that didn't work. Solved it by updating the Init() function of the control. _carouselView.VerticalOptions is initialized with EndAndExpand. Only when I changed that to FillAndExpand it strangely took the full height.

**Comment by masiri201** [comment]
yeahh, that's what happened to me, i will change it but it would be nice if it was updated on the NuGet Package aswell. thanks to you guys for aswering.

**Comment by chaosifier** [comment]
I've fixed the issue and included the changes in the new NuGet package version (1.0.3). Thank you for reporting the problem.

**Comment by ajaichemmanam** [comment]
I'm still having this issue. I can't set the tab view content to take the entire screen available. Itried with filla ndexpand and also endandexpand. Any Help?
