### ISSUE TITLE
Not running on UWP due to an exception

### ISSUE THREAD

**Issue by s2886676** [chaosifier/TabView#47]
Trying to run the sample project (from Github) on UWP but gives the following errors,
<img width="780" alt="Error" src="https://user-images.githubusercontent.com/7592030/99027155-8f9fce80-2592-11eb-89ed-165649a98ac0.PNG">

Also, to test it out on UWP.
Created a blank new project, added the Nuget package and initialized CarouselView in UWP. Added the TabView control in XAML, but doesnot work and throws "Object reference not set to an instance of an object" exception

**Comment by chaosifier** [comment]
Installing TabView plugin in the UWP project as well should fix the issue. It seems like you have only installed it in the shared library.

**Comment by s2886676** [comment]
I installed the plugin in UWP project and did the setup as recommended. But it still does not work.
I get this exception

System.ArgumentException: Delegate to an instance method cannot have null 'this'.
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at CarouselView.FormsPlugin.UWP.CarouselViewRenderer.FlipView_Loaded(Object sender, RoutedEventArgs e)
